trigger: none  # Only runs when triggered by Parent Pipeline

stages:
- stage: Build
  jobs:
  - job: BuildApp
    steps:
    - script: echo "Building the application..."
    - script: sleep 60  # Simulating work
    - script: echo "Build completed."