trigger: none  # This pipeline is manually triggered

stages:
- stage: StartPolling
  jobs:
  - job: TriggerChildPipelines
    steps:
    - script: echo "Triggering Child Pipelines"
    - task: AzureCLI@2
      inputs:
        azureSubscription: '<YourServiceConnection>'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Trigger Child Pipelines
          az pipelines run --name "ChildPipeline1" --org "https://dev.azure.com/YourOrg" --project "YourProject"
          az pipelines run --name "ChildPipeline2" --org "https://dev.azure.com/YourOrg" --project "YourProject"

- stage: MonitorChildPipelines
  dependsOn: StartPolling
  jobs:
  - job: PollChildStatus
    steps:
    - script: echo "Polling child pipelines status..."
    - task: AzureCLI@2
      inputs:
        azureSubscription: '<YourServiceConnection>'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Function to check child pipeline statuses
          check_status() {
            status1=$(az pipelines runs list --name "ChildPipeline1" --org "https://dev.azure.com/YourOrg" --project "YourProject" --query "[0].state" -o tsv)
            status2=$(az pipelines runs list --name "ChildPipeline2" --org "https://dev.azure.com/YourOrg" --project "YourProject" --query "[0].state" -o tsv)
            
            if [[ "$status1" == "completed" && "$status2" == "completed" ]]; then
              echo "All child pipelines completed."
              exit 0
            else
              echo "Waiting for child pipelines..."
              sleep 30
              check_status
            fi
          }
          check_status
