trigger: none  # Only runs when triggered by Parent Pipeline

stages:
- stage: Test
  jobs:
  - job: RunTests
    steps:
    - script: echo "Running tests..."
    - script: sleep 90  # Simulating work
    - script: echo "Tests completed."